Associations
NataJenkins/private-events pull request #1
Opened 2021-01-07 19:47 UTC by NataJenkins

Rails asociations to:

Create an event with an user, and be able to invite other users to the events.
users must be logged in to accept the invite to the events.

2021-01-07 21:33 UTC, blackpintz requested changes
# Status: Changes Required ✖️ 

### Hello team 😄,

**Great job on your project 💪. However, there a few fixes needed.**

1). **When I run `rails db:migrate`, I get the error shown below.**
![migration](https://user-images.githubusercontent.com/38922385/103940204-0f36bd80-513e-11eb-819b-36ccfd626a4d.png)

2). In the associations between the user and events, the user should be referenced as "creator" in the events model. Also, the events table should have the foreign key `creator_id` instead of `user_id`. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from Odin.

3).**The join model, `attendee.rb`, is incomplete. It should have something like the following**

```
class Attendee < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end
```
see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/attendee_assoc_requirement.png)t from Odin. 

4). **Since you are using a join model, attendee.rb, for your many-to-many relationships, you have to use the `has many through` method in user.rb and events.rb, to declare the associations. For example, in your user.rb model, you should have another line like the following**

```
class User < ActiveRecord::Base
has_many :attendees
has_many :attended_events, through: :attendees
end
```
You can reference this [article](https://guides.rubyonrails.org/association_basics.html#choosing-between-has-many-through-and-has-and-belongs-to-many) on how to use `has_many :through`. Please remember it has to be used in `events.rb` file too.

5). **The events index page should list all events separated into past and upcoming categories. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from Odin.**

6). **The user show page should list events created by user(see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from Odin), previously attended by user and upcoming events to be attended by user. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from Odin.**

7).**There should be no conditional logic(if statements and each loops) in your views directory files. Please remove it and instead write it in Views helpers `(app/helpers/*_helper.rb)`. You can reference the following articles on this: [article1](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers), [article2](http://codefol.io/posts/Where-Do-I-Put-My-Code/).**

8). **Add Rspec tests as described in the screenshot below from pathwright.**
![rspec_tests](https://user-images.githubusercontent.com/38922385/103946616-e0254980-5147-11eb-957e-10c0dff6afdb.png)

9). **Please see one comment below.**


### Optional
1). Define routes for only used actions.

## Happy coding 🥂 

**PS: You can reach me on slack (Rose Wanjohi).**

2021-01-07 21:33 UTC, blackpintz commented on db/schema.rb
> +  end
Index the `user_id` and `event_id` keys.

2021-01-11 17:08 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] When running the `rails server` command, this error message appears on the browser
![image](https://user-images.githubusercontent.com/25774518/104209585-89459b80-53f7-11eb-8bf4-b4f897e85be2.png)
- [x] Trying to figure out the cause and commenting the past line (not the best solution) of code also throws an error with line `9`  of the `./app/views/layouts/application.html.erb`
![image](https://user-images.githubusercontent.com/25774518/104210344-623b9980-53f8-11eb-89a8-7d534e5ece34.png)
  - NOTE: Commenting both lines let me run the application on the browser. Please find out what's going on and make it work with the code in the repository or change if necessary.

- [x] Users can't logout
![image](https://user-images.githubusercontent.com/25774518/104211850-328d9100-53fa-11eb-98f7-840bfcb5502a.png)

- [x] 3).The join model, `attendee.rb`, is incomplete. It should have something like the following **STILL PENDING**
> 
> ```
> class Attendee < ApplicationRecord
>   belongs_to :attendee, class_name: "User"
>   belongs_to :attended_event, class_name: "Event"
> end
> ```

> see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/attendee_assoc_requirement.png)t from Odin.
>

- [ ] 5). The events index page should list all events separated into past and upcoming categories. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from Odin.

  **STILL PENDING:  I've seen that when creating an event it identifies each new event as `past` or `future` event, this is great but still is not separating past from upcoming, as a recommendation create on the view a list for each and depending on the date will the event will be added to this list.**

- [ ] 6). The user show page should list events created by user(see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from Odin), previously attended by user and upcoming events to be attended by user. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from Odin.

  **STILL PENDING:  Please fix first the logout issue and check this point is working before submitting for a re-review.** 

- [ ] 7).There should be no conditional logic(if statements and each loops) in your views directory files. Please remove it and instead write it in Views helpers `(app/helpers/*_helper.rb)`. You can reference the following articles on this: [article1](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers), [article2](http://codefol.io/posts

  **STILL PENDING: To solve this create helpers that will accept an argument and will apply the logic in the same way you have it the views, the difference is that the helper will be stored in the `helpers` section of the application structure. A helper is just a ruby method that returns whatever you want. In this way instead of using logic inside the view, you will only call the newly created helper( or ruby method)**

- [ ] 8). Add Rspec tests as described in the screenshot below from pathwright.
> ![rspec_tests](https://user-images.githubusercontent.com/38922385/103946616-e0254980-5147-11eb-957e-10c0dff6afdb.png)

  **STILL PENDING: Log out should also be tested and also elements related to creating, updating, viewing, and deleting events.**

### [OPTIONAL] :large_blue_circle: 
- [ ] The Gem `wdm` could cause your project to stop working correctly on Linux or Unix OS please add this to your Gemfile so it doesn't crash when running `bundle install`
```
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
```


## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2021-01-11 18:58 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] When trying to create an attendee this error appears in the console
![image](https://user-images.githubusercontent.com/25774518/104223698-92d7ff00-5409-11eb-8933-fe482b531e4d.png)
- [ ] Event's index page displays past and upcoming **events lists**, as I mentioned before not just identify which one is _future_ and which one is _past_. They should be separated on a list.
  > * [x]  5). The events index page should list all events separated into past and upcoming categories. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from Odin.
  >   **STILL PENDING:  I've seen that when creating an event it identifies each new event as `past` or `future` event, this is great but still is not separating past from upcoming, as a recommendation create on the view a list for each and depending on the date will the event will be added to this list.**
- [ ] There is no navigation with buttons to move around the page to move around the page
- [ ] Event's show page doesn't display the list of attendees. As users can't invite other users to the event.
- [ ] The user's show page displays events the user has created and events that the user is attending, also these events should be separated in past and upcoming
  > * 6). The user show page should list events created by user(see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from Odin), previously attended by user and upcoming events to be attended by user. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from Odin.
  >   **STILL PENDING:  Please fix first the logout issue and check this point is working before submitting for a re-review.**
- [ ] There should be no logic in the view, please review your views even the partials, and remove the logic from within.
  > * [ ]  7).There should be no conditional logic(if statements and each loops) in your views directory files. Please remove it and instead write it in Views helpers `(app/helpers/*_helper.rb)`. You can reference the following articles on this: [article1](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers), [article2](http://codefol.io/posts
  >   **STILL PENDING: To solve this create helpers that will accept an argument and will apply the logic in the same way you have it the views, the difference is that the helper will be stored in the `helpers` section of the application structure. A helper is just a ruby method that returns whatever you want. In this way instead of using logic inside the view, you will only call the newly created helper( or ruby method)**

- [ ] Integration testing is missing some specs
  > * 8). Add Rspec tests as described in the screenshot below from pathwright.
  > 
  > > ![rspec_tests](https://user-images.githubusercontent.com/38922385/103946616-e0254980-5147-11eb-957e-10c0dff6afdb.png)
  > 
  > **STILL PENDING: Log out should also be tested and also elements related to creating, updating, viewing, and deleting events.**

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2021-01-11 23:14 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] after creating an event, I get an error whenever I try to visit the event's page, stopping me from completing my review
![image](https://user-images.githubusercontent.com/11758151/104249062-fba39380-546a-11eb-8fc7-1d8004beea89.png)
**_you're comparing a string to an integer, convert the string then compare_**

- [x] when I go to a specific event and click "create attendee" the button wouldn't work.
- [x] please remove the logic from your views ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)
- [x] add more tests
  * [ ] models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
  * [ ] authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
  * [ ] event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-12 20:17 UTC, mimipeshy commented
### STATUS : CHANGES REQUIRED :red_circle: :recycle: 

Hey team @NataJenkins and @Nexch :wave: :wave: good job so far. However, a few things need to be completed before we can mark the project as complete 

- [ ]  Event's index page should display past and upcoming events lists ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [ ] The event's show page displays the list of attendants ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [ ]The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [ ] Navigation links are present at the top of the page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [ ]  when I go to a specific event and click "create attendee" the button wouldn't work.

That's all :smile: , kindly submit another review when done.
If you have any questions kindly drop me a message on slack i will be glad to help

Regards
Peris Ndanu

2021-01-13 03:34 UTC, voscarmv requested changes
# Impressive work, team. 💻 👀 ✨ 

- Your app seems to work fine.

## However, there are some changes required 👀 🧰 🔨 🔧 

- I'm able to create events with blank dates. This in turn breaks the `/events` view because the application can't really display events with blank dates. Please fix this!

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-01-13 14:32 UTC, jubaan approved these changes
# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

#### :clap: :clap: Great job :hammer_and_pick:!! There are no more issues left to be addressed. 

## See you at the top :rocket:!

# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

2021-01-15 21:39 UTC, merged